version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./WeTin-React:/app/WeTin-React 

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
      - ./default.conf:/etc/nginx/conf.d/default.conf 
      - ./build:/usr/share/nginx/html
    depends_on:
      - app  
