version: "3.8"

services:
  build-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: build-container
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - CI=true

  nginx-container:
    image: nginx:alpine
    container_name: nginx-container
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - build-container 