version: '3'
services:
  frontend-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/app/build

  nginx:
    image: nginx:latest
    depends_on:
      - frontend-builder
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
