name: Deploy to VM

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: multiple command
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
      
          if [ -d "/caminho/para/WeTin-React" ]; then
            cd /caminho/para/WeTin-React
            git pull
          else
            git clone https://seu-repo-url.git /caminho/para/WeTin-React
            cd /caminho/para/WeTin-React
          fi
          npm install
