name: Docker Publish

on:
  push:
    branches:
      - main  # Define que o workflow será executado quando houver push na branch `main`.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Faz checkout do código no repositório.

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          cd wetin/
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-wetin:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/frontend-wetin:latest ${{ secrets.DOCKER_USERNAME }}/frontend-wetin:${{ github.sha }}
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-wetin:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-wetin:${{ github.sha }}
