name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Go to project directory
        run: cd wetin

      - name: Install dependencies
        run: |
          cd wetin
          npm install

      - name: Build project
        run: |
          cd wetin
          npm run build

  docker-publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          cd wetin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-wetin:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/frontend-wetin:latest ${{ secrets.DOCKER_USERNAME }}/frontend-wetin:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-wetin:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-wetin:${{ github.sha }}

  update-ec2:
    runs-on: 
      - self-hosted
      - frontend
      - wetin
    needs: docker-publish

    steps:
      - name: Atualizar Imagem do Frontend no Docker
        run: |
          echo "Fazendo pull da última imagem..."
          docker pull jpedroduarte123/frontend-wetin:latest
          
          echo "Parando container antigo..."
          docker stop frontend-wetin || true
          
          echo "Removendo container antigo..."
          docker rm frontend-wetin || true
          
          echo "Iniciando novo container..."
          docker run -d --name frontend-wetin -p 3000:3000 jpedroduarte123/frontend-wetin:latest
